version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: raw_eoh_viajeros_localidad
      - name: raw_eoh_pernoctes_localidad
      - name: raw_trends_sde
      - name: raw_bcra_tcn
      - name: raw_anac_sde
      - name: raw_cnrt_pares
      - name: raw_eti_serie_mensual
      - name: raw_youtube_sde
      - name: raw_airdna_base
